In [ ]:
numbers=[10,20,30,40,50]
print(numbers[0])
print(numbers[-1])
print(numbers[1:4])


10
50
[20, 30, 40]


In [ ]:
numbers.append(60)
print(numbers)

[10, 20, 40, 60]


In [ ]:
print(len(numbers))

4


In [ ]:
type(numbers)

list

In [ ]:
numbers[2]=40
numbers

[10, 20, 40]

In [ ]:
numbers.count(40)

2

In [ ]:
numbers.index(50)

4

In [ ]:
numbers.remove(40)
print(numbers)

[10, 20, 50]


In [ ]:
numbers.insert(2,17)
print(numbers)

[10, 20, 17, 40, 60]


In [ ]:
numbers

[10, 20, 40, 40, 21, 50]

In [ ]:
numbers.extend([10,40])
print(numbers)

[10, 20, 17, 40, 60, 10, 40]


In [ ]:
numbers.append([17,15,25,35])
print(numbers)

[10, 20, 17, 40, 60, 10, 40, [17, 15, 25, 35]]


In [ ]:
numbers[1]

20

In [ ]:
example=[2,1,5,4,7]
example. sort()
example

[1, 2, 4, 5, 7]

In [ ]:
example. reverse()
example

[7, 5, 4, 2, 1]

In [ ]:
new=example. copy()
new

[7, 5, 4, 2, 1]

In [ ]:
numbers. clear()
numbers

[]

In [ ]:

numbers = [10, 20, 30, 40]
del numbers[2]
print(numbers)




[10, 20, 40]


In [ ]:
digits=(1,23, )

In [ ]:
numbers=(10,20,30,32)
print(numbers)
print(numbers.count(20))
print(numbers.index(30))
print(len(numbers))
print(sorted(numbers))
print(type(numbers))


(10, 20, 30, 32)
1
2
4
[10, 20, 30, 32]
<class 'tuple'>


In [ ]:
set={10,20,30,20,40}
set

{10, 20, 30, 40}

In [ ]:
set.add(40)
set


{10, 20, 30, 40}

In [ ]:
set.remove(10)
set

{20, 30, 40}

In [ ]:
set.add(80)
set

{20, 30, 40, 80}

In [ ]:
set.update({90,50})
set

{20, 30, 40, 50, 80, 90}

In [ ]:
set.clear()
set

set()

In [ ]:
print(10 in set)
set

False


set()

In [ ]:
len(set)
set

set()

In [ ]:
set.discard(50)
set

set()

In [ ]:
set={10,20,30,40}
set.discard(10)
set

{20, 30, 40}

In [ ]:
set.discard(69)

In [ ]:
a={1,2,3,4,5,6,7}
b={5,6,7}
print(a.union(b))

{1, 2, 3, 4, 5, 6, 7}


In [ ]:
b={2,4,6,8,9,4,6,9}
print(a|b)

{1, 2, 3, 4, 5, 6, 7, 8, 9}


In [ ]:
print(a-b)

{1, 3, 5, 7}


In [ ]:
print(a&b)

{2, 4, 6}


In [ ]:
print(a^b)

{1, 3, 5, 7, 8, 9}


In [ ]:
a, b, c = 10, 15, 13

if a > b:
    if a > c:
        print("A is largest number")
    else:
        print("C is largest number")
else:
    if b > c:
        print("B is largest number")
    else:
        print("C is largest number")

B is largest number


In [ ]:
day=int(input("enter the day number:"))
match day:
  case 1:print("Monday")
  case 2:print("Tuesday")
  case 3:print("Wednesday")
  case 4:print("Thursday")
  case 5:print("Friday")
  case 6:print("Saturday")
  case 7:print("Sunday")
  case _:print("Invalid day")

enter the day number:4
Thursday


In [ ]:
num = 153
temp = num
sum = 0

while num != 0:
    rem = num % 10
    sum = sum + rem ** 3
    num = num // 10

if sum == temp:
    print("Armstrong Number")
else:
    print("Not Armstrong Number")

Armstrong Number


In [ ]:
num=4
i=1

while i<=10:
  print(num,"x",i,"=",num*i)
  i=i+1

4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40


In [ ]:
fact=1
i=1

while i<=5:
  fact*=i
  i+=1
print("factorial number is :",fact)

factorial number is : 120


In [ ]:
num=int(input("enter the number value:"))
i=2

while i<num:
  if num % i==0:
    print("not prime number")
    break
  i +=1
else:
  print("prime number")

enter the number value:7
prime number


In [ ]:
sum=0
i=1
while i<=10:
  sum=sum+i
  i=i+1
  print("sum of N natural numbers is:",sum)

sum of N natural numbers is: 1
sum of N natural numbers is: 3
sum of N natural numbers is: 6
sum of N natural numbers is: 10
sum of N natural numbers is: 15
sum of N natural numbers is: 21
sum of N natural numbers is: 28
sum of N natural numbers is: 36
sum of N natural numbers is: 45
sum of N natural numbers is: 55


In [ ]:
num=7
count=0
for i in range(1,num+1):
  if num%i==0:
    count+=1

if count==2:
  print("prime number")
else:
  print("not prime number")

prime number


In [ ]:
n=int(input("enter the number of terms:"))
a=0
b=1
b=1
while i<=n:
  print(a)
  c=a+b
  b=a
  a=c
  i+=1

enter the number of terms:20
0
1
1
2
3
5
8
13
21
34
55


In [ ]:
n1,n2=0,1
for i in range(2,12):
  print(n1,end=" ")
  n1, n2=n2,n1+n2

0 1 1 2 3 5 8 13 21 34 

In [ ]:
def fun():
 print("hello world")

fun()
fun()
fun()
fun()




hello world
hello world
hello world
hello world


In [ ]:
def add(x,y):
  print("addition of two numbers is:",x+y)

add(100,200)
add(23,12)
add(89,99)
add(55,1001)



addition of two numbers is: 300
addition of two numbers is: 35
addition of two numbers is: 188
addition of two numbers is: 1056


In [ ]:

def details(USN_number,name,college,place,marks,sem):
    print(f"My name is {name}. I'm studying in {sem} semester in {college} college at {place}. My last semester marks is {marks} and my USN number is {USN_number}")

details(162,"varsha","KLE","gadag",457,"5th")

details("U02FI25S0162","abhay","JT College","chikkodi",555,"4th")


My name is varsha. I'm studying in 5th semester in KLE college at gadag. My last semester marks is 457 and my USN number is 162
My name is abhay. I'm studying in 4th semester in JT College college at chikkodi. My last semester marks is 555 and my USN number is U02FI25S0162


In [ ]:
def information(emp_id,emp_name,emp_age,emp_salary,company_name,location,phone_number):
    print(f"Employee ID is {emp_id}")
    print(f"Employee name is {emp_name}")
    print(f"Employee age is {emp_age}")
    print(f"Employee salary is {emp_salary}")
    print(f"Company name is {company_name}")
    print(f"Location is {location}")
    print(f"Phone number is {phone_number}")


information(101,"Varsha",25,30000,"Infosys","Bangalore",9876543210)

Employee ID is 101
Employee name is Varsha
Employee age is 25
Employee salary is 30000
Company name is Infosys
Location is Bangalore
Phone number is 9876543210


In [ ]:
def hello(country="india 🚩"):
  print("i love",country)

hello(" india")
hello("bangladesha")
hello("america")
hello()


i love  india
i love bangladesha
i love america
i love india 🚩


In [ ]:
def student(*marks):
    total = 0
    for i in marks:
        total = total + i
    print("Total num value is:", total)

student(1,2,3,4,5)
student(5,10,25,40,55,70,95,110)

Total num value is: 15
Total num value is: 410


In [ ]:
def fun(**Kwargs):

  for key,value in Kwargs.items():
    print(f"{key} : {value}")

fun(reg=121,name="basava",age=23,place="raichur")

reg : 121
name : basava
age : 23
place : raichur


In [94]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [96]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [97]:
import numpy as np
arr=np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [98]:
import numpy as n
arr=n.zeros((10,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [102]:
import numpy as np
arr=np.ones((5,7))
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [100]:
import numpy as np
arr=np.full((4,7),9)
print(arr)


[[9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]]


In [103]:
import numpy as np
arr=np.empty((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [104]:
import numpy as np
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [1]:
import numpy as np
arr = np.arange(2,100)
print(arr)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]


In [2]:
name="akshuu"
print(name)

akshuu


In [7]:
import numpy as np
Even=np.arange(2,200,2)
print(Even)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198]


In [14]:
import numpy as np
Odd=np.arange(1,200,2)
print(Odd)

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199]


In [16]:
import numpy as np
arr = np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [17]:
import numpy as np
arr = np.linspace(1,20,7)
print(arr)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [19]:
import numpy as np
arr = np.random.rand(10)
print(arr)

[0.84759753 0.60750655 0.0764634  0.05144152 0.11935762 0.18168797
 0.87932776 0.19353594 0.45487683 0.53139868]


In [22]:
import numpy as np
arr = np.random.randn(10)
print(arr)

[-0.60936974  0.80433403 -0.52318141  1.35514533  0.53654934  1.10804328
  0.41707082  1.72322093 -0.75189048  0.97554757]


In [25]:
import numpy as np
arr = np.random.randint(100)
print(arr)

64


In [37]:
import numpy as np
colours=["red","green","pink","orange","blue","white","black"]
print(np.random.choice(colours,2))

['white' 'black']


In [38]:
import numpy as np
arr=np.array([1,2,3])
new=arr.copy()
new[1]=100
print("array value is:",arr)
print("copy value is :",new)

array value is: [1 2 3]
copy value is : [  1 100   3]


In [40]:
import numpy as np
arr=np.array([1,2,3])
new=arr.view()
new[1]=100
print("array value is:",arr)
print("view value is:",new)

array value is: [  1 100   3]
view value is: [  1 100   3]


In [41]:
import numpy as np
arr=np.array([5,10,15,20,25,30])
arr +=10
print("updated array value is:",arr)

updated array value is: [15 20 25 30 35 40]


In [42]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.add(A,B))


[ 7  9 11 13 15]


In [43]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.subtract(A,B))


[-5 -5 -5 -5 -5]


In [44]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.multiply(A,B))


[ 6 14 24 36 50]


In [45]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.divide(A,B))


[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [46]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.dot(A,B))


130


In [47]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(sum(arr))

45


In [51]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.max())

9


In [52]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.min())

1


In [54]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.mean())

5.0


In [55]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.std())

2.581988897471611


In [77]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [59]:
import numpy as np
arr=np.array([9,4,7,3,8,9,4,1])
print(np.sort(arr))

[1 3 4 4 7 8 9 9]


In [61]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,1,2,1,2,9])
print(np.unique(arr))

[1 2 3 4 5 6 7 8 9]


In [68]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.shape)
print(arr.size)
print(arr.itemsize)
print(arr.ndim)
print(arr.dtype)

(9,)
9
8
1
int64


In [76]:
import numpy as np
arr=np.array([[1,2,3,4],[5,4,3,2]])
print(arr.shape)
print(arr.ndim)
print(arr[0,1])
print(arr[1,1])
print(arr[:,1])

(2, 4)
2
2
4
[2 4]


In [78]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,99,10,11,12,13,14,15])
print("original array",arr)
new=arr.reshape(5,3)
print(new)

original array [ 1  2  3  4  5  6  7  8 99 10 11 12 13 14 15]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 99]
 [10 11 12]
 [13 14 15]]
